rules:
  indentation:
    - 1
    - size: 2
  mixins-before-declarations: 2
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 1
  no-trailing-zero: 2
  no-transition-all: 2
  no-vendor-prefixes: 2
  no-warn: 2
  leading-zero: 2
  space-after-comma: 2
  space-after-colon: 2
  space-before-brace: 2
  trailing-semicolon: 2
  final-newline: 2
  property-sort-order: 0
  no-url-protocols: 0
  class-name-format: 0
  nesting-depth:
    - 1
    -
      max-depth: 4
